print("               ^")
print("              /^\\")
print("             /___\\")
print("            |=   =|")
print("            |     |")
print("            |NASA |")
print("            |     |")
print("            |     |")
print("           /|##!##|\\")
print("          / |##!##| \\")
print("         /  |##!##|  \\")
print("        |  /^^^^^^^\\  |")
print("        | /  🚀     \\ |")
print("        |/___________\\|")
print("             /   \\")
print("            /_____\\")
print("             | | |")
print("             | | |")
print("            *********")